kind: Pod
apiVersion: v1
metadata:
   name: pod-red
   labels:
    app: web
spec:
   containers:
   - name: webapp-color-red
     image: mmumshad/simple-webapp-color
     ports:
      - containerPort: 8080
     env:
       - name: APP_COLOR
         value: "red"
