kind: Pod
apiVersion: v1
metadata:
   name: mysql-pv
spec:
   volumes:
    - name: data-volume
      persistentVolumeClaim:
       claimName: pv-claim

   containers:
    - name: mysql-pv
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password 
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: easy
        - name: MYSQL_PASSWORD
          value: easy
      volumeMounts: 
        - name: data-volume
          mountPath: /var/lib/mysql


