kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
spec:
   capacity:
      storage: 1Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   hostPath:
      path: "/mnt/data"
